# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b10bbe43a97c999a1db2ec6b4106e026088c477b7e14f6c15588a52edfe21a6d9fcd9f2b19e5e824de40b1d5271dba85febe099fe657dde448b7c4fcfb847b20

test:
  secret_key_base: 9545195228aee647aa1d4a35176b6c93f663f3a96e006efb45c3eda3c739f8fd6c99e22b6c815eb17c79a02e1ed6afb56bea0d439fb4cb88477a63adb1df137d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
